### PR TITLE
Allow "- var" and "-" statements for declaring variables within templates

### PR DESCRIPTION
**Pull request by larsonjj**
Currently, there isn't any support for `- var someVar = "someString"` or `- someVar = "someString"` statements. They must be `someVar = "someString"`. This breaks compatibility with the official Jade library. So to remedy this issue, a RegEx replace statement has been added that looks for the `- var` or `-` statements, removes them, and lets the Scanner continue on normally.

### CODE REVIEW

**Comment by naltatis** [comment]
Thanks for the PR! Il will test it out in the next days.

**Comment by marlonbernardes** [comment]
Recompiling the regular expression inside a loop (`Pattern.compile`) could severely hurt performance.

**Comment by larsonjj** [comment]
Any update here?

**Comment by marlonbernardes** [comment]
@larsonjj  this repo is not active anymore.

**Comment by chbloemer** [comment]
This feature should be in 1.0.0 and up. So, close this Pull-Request.

**Pull request closed without merging**
