### PR TITLE
Allow mixin definitions in layout extensions

### PR DESCRIPTION
**Pull request by rzara**
Jade allows mixin to be defined, directly or via an include, in
layout extensions.

fixes issue #104

### CODE REVIEW

**Comment by FinalGuy** [comment]
Hi rzara,
thank you for contribution. We will check your pull request.

**Comment by chbloemer** [comment]
Hi,
could you please check out if the new 1.0.0 Version fixes your problem. There is a very similiar testcase (inheritance.extend.mixins.jade).

Greetingz
Christoph

**Comment by rzara** [comment]
Hi,
1.0.3 does not fix the problem. If you enable the inheritance.extend.mixins.jade test, it fails.
Regards,
Rémi

**Comment by rzara** [comment]
I pushed an updated fix. All tests should be passing, including inheritance.extend.mixins.jade which I enable.

**Comment by chbloemer** [comment]
Thank you. I will release a Version 1.0.4 later this day.

**Pull request merged**
