### PR TITLE
Fix failed tests on Java 8: issue #67.

### PR DESCRIPTION
**Pull request by IRus**
Use order-guarantied data structures. (fix issue #67 )

Build on CI: https://travis-ci.org/IRus/jade4j/builds/57764072

### CODE REVIEW

**Comment by waldemar-schneider** [comment]
It seems you also had the same problem, as I described them in issue #86. I made a pull request (#88) a long time ago.

**Comment by IRus** [comment]
@waldemar-schneider yea, not noticed. I close this.

**Comment by IRus** [comment]
@waldemar-schneider please, take a look at IterableMap file and our changes. I think i use better way to fix.

**Comment by waldemar-schneider** [comment]
Sorry for the late response. I think you are right about the implementation of IterableMap. Maybe some of the owners could make finally a review?

**Comment by IRus** [comment]
@naltatis As you can see now built failed on jdk8 because of using HashMap that don't guaranteed iteration order. I nicely fix this by replacing HashMap with LinkedHashMap.

**Comment by naltatis** [comment]
Thanks, now all test pass again.

**Comment by IRus** [comment]
It's great! Thank you!

**Pull request merged**
